dbfilename redis_queue.rdb
dir /Users/gianpaulocoletti/frappe-1/start/config/pids
pidfile /Users/gianpaulocoletti/frappe-1/start/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /Users/gianpaulocoletti/frappe-1/start/config/redis_queue.acl
